# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# The assistant project unique identifier
# This default value must be replaced with a unique assistant name within your deployment
assistant_id: 20250716-223904-grave-carrier

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

# Optimized pipeline for medical chatbot with enhanced NLU
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: word
    min_ngram: 1
    max_ngram: 2
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 150
    constrain_similarities: true
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 150
    constrain_similarities: true
  - name: FallbackClassifier
    threshold: 0.25
    ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
# Optimized policies for medical chatbot with form handling and API integration
policies:
  - name: MemoizationPolicy
    max_history: 5
  - name: RulePolicy
    core_fallback_threshold: 0.25
    core_fallback_action_name: "action_llm_fallback"
    enable_fallback_prediction: true
  - name: UnexpecTEDIntentPolicy
    max_history: 5
    epochs: 150
  - name: TEDPolicy
    max_history: 8
    epochs: 150
    constrain_similarities: true
